// Code generated by MockGen. DO NOT EDIT.
// Source: common.go
//
// Generated by this command:
//
//	mockgen -source=common.go -destination=mock/common.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/art-es/yet-another-service/internal/domain/shared/models"
	gomock "go.uber.org/mock/gomock"
)

// MockmailRepository is a mock of mailRepository interface.
type MockmailRepository struct {
	ctrl     *gomock.Controller
	recorder *MockmailRepositoryMockRecorder
	isgomock struct{}
}

// MockmailRepositoryMockRecorder is the mock recorder for MockmailRepository.
type MockmailRepositoryMockRecorder struct {
	mock *MockmailRepository
}

// NewMockmailRepository creates a new mock instance.
func NewMockmailRepository(ctrl *gomock.Controller) *MockmailRepository {
	mock := &MockmailRepository{ctrl: ctrl}
	mock.recorder = &MockmailRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmailRepository) EXPECT() *MockmailRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockmailRepository) Save(ctx context.Context, mails []models.Mail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, mails)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockmailRepositoryMockRecorder) Save(ctx, mails any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockmailRepository)(nil).Save), ctx, mails)
}
